---
language: rust
dist: xenial
rust:
  - stable
  - beta
  - nightly
env:
  - CRATE=core
  - CRATE=server
  - CRATE=web-client
  - CRATE=processors/git-clone
  - CRATE=processors/http-request
  - CRATE=processors/json-edit
  - CRATE=processors/print-output
  - CRATE=processors/redis-command
  - CRATE=processors/shell-command
  - CRATE=processors/sql-query
  - CRATE=processors/string-regex
cache: false
stages:
  - build
  - test
  - release
jobs:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - stage: build
      script: echo build stage!
      rust: stable
      env: CRATE=
    - stage: test
      script: echo "testing crate $CRATE"
    - stage: release
      script: echo "releasing!"
      rust: stable
      env: CRATE=
